experiment_path: ./experiments/2025-9-4-0

img_size: [256,256,1]
num_classes: 4
model_path: ./best_unet.h5

weight_in_ce: [0.1,50,8,1]
weight_of_dice: 0.5
ignore_background: false
deep_supervision: false

batch_size: 16
epochs: 20
learning_rate: 3e-4

load_weight_path: 