experiment_path: ./experiments/2025-9-11-1

img_size: [256,256,3]
num_classes: 4
model_path: ./best_unet.h5

weight_in_ce: [0.1,2,1,1]
weight_of_dice: 0.5
ignore_background: True

batch_size: 16
epochs: 4
learning_rate: 3e-5

load_weight_path: 